### ISSUE TITLE
Part of the NSD data is not downloadable via the web interface

### ISSUE THREAD

**Issue by mathalex** [kendrickkay/nsddatapaper#2]
I found that part of the NSD data is not downloadable via the web interface at https://natural-scenes-dataset.s3.amazonaws.com/index.html

I want to download all timeseries from "nsddata_timeseries/ppdata/subj0*/func1pt8mm/timeseries/", where * is 1, 2, 3, ..., 8.
I have noticed that all timeseries that were uploaded on 2020-12-20 are available for downloading. Meanwhile, others were uploaded on 2021-03-06 and attempts to download them led to an "Access Denied" error.

Statistics of how many sessions are available for each subject:
1: 37/40
2: 37/40
3: 29/32
4: 27/30
5: 37/40
6: 29/32
7: 37/40
8: 27/30

Clearly, the last three sessions of each subject are unavailable for downloading by link.
Therefore, I am asking you to grant access to these files so they can be downloadable via HTTPS using open-source tools such as curl/wget, not the proprietary AWS S3 client.

**Comment by kendrickkay** [comment]
These last several scans are held-out from public release at the moment. This is documented on the Data Manual.
