### ISSUE TITLE
Lack of Brain Region Labels for NIfTI Values in NSD Dataset

### ISSUE THREAD

**Issue by Zhangzhixiang-laugh** [kendrickkay/nsddatapaper#5]
**Description:**

The NSD dataset provides a variety of different atlases based on existing research, which is very useful. However, it does not include labels for the brain regions corresponding to the different values in the NIfTI files. This makes it challenging to map brain regions to the atlases, hindering research efforts that require this level of detail. 

**It would be greatly beneficial to have a mapping of NIfTI values to brain region names** （Especially for MTL, HCP_MMP1, and thalamus, etc.） to facilitate a clearer understanding of how different brain areas are represented in the provided atlases.

**Suggested Improvement:**

Please consider including a mapping file or a detailed list that correlates NIfTI values with specific brain regions, either as part of the dataset or as supplementary information.
![image](https://github.com/user-attachments/assets/8cca0af1-e5e2-47da-b2c4-928457f8e171)

**Comment by kendrickkay** [comment]
Please see this part of the NSD Data Manual:


￼

**Comment by kendrickkay** [comment]
<img width="414" alt="image" src="https://github.com/user-attachments/assets/ead6c96b-e769-461a-9c68-47de7b38cafd" />

**Comment by Zhangzhixiang-laugh** [comment]
> <img alt="image" width="414" src="https://private-user-images.githubusercontent.com/2728338/395816968-ead6c96b-e769-461a-9c68-47de7b38cafd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyMjA4NzgsIm5iZiI6MTczNDIyMDU3OCwicGF0aCI6Ii8yNzI4MzM4LzM5NTgxNjk2OC1lYWQ2Yzk2Yi1lNzY5LTQ2MWEtOWM2OC00N2RlN2IzOGNhZmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTRUMjM1NjE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGM2MGYxYzYyMDc2MmU0NzAwNmRjYWQzNDUzYzNmODI5ZDRhNzgxYzBjMjZmODU1MmMyYzFhMTE5MzJiM2IwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ZIIeWdVeF2UXEVwkFcofjWMtXJ28qSki9z2xDxx8y9A">

Thanks!
